//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMRT.Test.Linq.SivgkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sivgk:services:notification-link", ConfigurationName="SivgkService.InformationLinkPortType")]
    public interface InformationLinkPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sivgk:services:notification-link#get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAMRT.Test.Linq.SivgkService.getResponse get(SAMRT.Test.Linq.SivgkService.getRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sivgk:services:notification-link#get", ReplyAction="*")]
        System.Threading.Tasks.Task<SAMRT.Test.Linq.SivgkService.getResponse> getAsync(SAMRT.Test.Linq.SivgkService.getRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sivgk:services:notification-link-types")]
    public partial class NotificationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private informationSystemData fromField;
        
        private informationSystemData toField;
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public informationSystemData from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public informationSystemData to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sivgk:services:notification-link-types")]
    public partial class informationSystemData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sivgk:services:notification-link-types")]
    public partial class revision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string revision1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revision", Order=1)]
        public string revision1 {
            get {
                return this.revision1Field;
            }
            set {
                this.revision1Field = value;
                this.RaisePropertyChanged("revision1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:sivgk:services:notification-link-types")]
        public SAMRT.Test.Linq.SivgkService.NotificationHeader NotificationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=0)]
        public string accessToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=1)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=2)]
        public SAMRT.Test.Linq.SivgkService.revision revision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=3)]
        public string filter;
        
        public getRequest() {
        }
        
        public getRequest(SAMRT.Test.Linq.SivgkService.NotificationHeader NotificationHeader, string accessToken, string type, SAMRT.Test.Linq.SivgkService.revision revision, string filter) {
            this.NotificationHeader = NotificationHeader;
            this.accessToken = accessToken;
            this.type = type;
            this.revision = revision;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=0)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=1)]
        public SAMRT.Test.Linq.SivgkService.revision revision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sivgk:services:notification-link-types", Order=2)]
        public System.Xml.XmlElement data;
        
        public getResponse() {
        }
        
        public getResponse(string type, SAMRT.Test.Linq.SivgkService.revision revision, System.Xml.XmlElement data) {
            this.type = type;
            this.revision = revision;
            this.data = data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InformationLinkPortTypeChannel : SAMRT.Test.Linq.SivgkService.InformationLinkPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationLinkPortTypeClient : System.ServiceModel.ClientBase<SAMRT.Test.Linq.SivgkService.InformationLinkPortType>, SAMRT.Test.Linq.SivgkService.InformationLinkPortType {
        
        public InformationLinkPortTypeClient() {
        }
        
        public InformationLinkPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationLinkPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationLinkPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationLinkPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAMRT.Test.Linq.SivgkService.getResponse SAMRT.Test.Linq.SivgkService.InformationLinkPortType.get(SAMRT.Test.Linq.SivgkService.getRequest request) {
            return base.Channel.get(request);
        }
        
        public System.Xml.XmlElement get(SAMRT.Test.Linq.SivgkService.NotificationHeader NotificationHeader, string accessToken, ref string type, ref SAMRT.Test.Linq.SivgkService.revision revision, string filter) {
            SAMRT.Test.Linq.SivgkService.getRequest inValue = new SAMRT.Test.Linq.SivgkService.getRequest();
            inValue.NotificationHeader = NotificationHeader;
            inValue.accessToken = accessToken;
            inValue.type = type;
            inValue.revision = revision;
            inValue.filter = filter;
            SAMRT.Test.Linq.SivgkService.getResponse retVal = ((SAMRT.Test.Linq.SivgkService.InformationLinkPortType)(this)).get(inValue);
            type = retVal.type;
            revision = retVal.revision;
            return retVal.data;
        }
        
        public System.Threading.Tasks.Task<SAMRT.Test.Linq.SivgkService.getResponse> getAsync(SAMRT.Test.Linq.SivgkService.getRequest request) {
            return base.Channel.getAsync(request);
        }
    }
}
